// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StaffForm.Entity
{
    public partial class StaffDetailTable
    {
        public int Staff_ID { get; set; }
        public string Staff_Name { get; set; }
        public int User_Age { get; set; }
        public string User_Gender { get; set; }
        public string User_Qualification { get; set; }
        public string Company_Name { get; set; }
        public DateTime Joining_Date { get; set; }
        public string Position { get; set; }
        public int Staff_Location_ID { get; set; }
        public int Year_Of_Experience { get; set; }
        public string User_Address { get; set; }
        public long Mobile_No { get; set; }
        public string Email_ID { get; set; }
        public string User_Password { get; set; }
        public string Conform_Password { get; set; }
        public bool Is_Deleted { get; set; }
        public DateTime Created_Time_Stamp { get; set; }
        public DateTime Updated_Time_Stamp { get; set; }

        public virtual Staff_Location Staff_Location { get; set; }
    }
}